### PR TITLE
Use Conan for easier dependency management

### PR DESCRIPTION
**Pull request by bdhobare**
[Conan.io](https://conan.io/) is a popular dependency management tool for C/C++ projects. It relieves us of the troubles of manually managing each library in CMake.

- Added support for Conan for easier dependency management.
- Updated the build guide.

**Note**
*Building libcurl with gcc-9+ on MacOS currently fails because of [this issue] (https://github.com/curl/curl/issues/4821). Try clang if this happens.*

### CODE REVIEW

**Comment by Sfinx** [comment]
: Building libcurl with gcc-9+ on MacOS currently fails because of [this issue] (curl/curl#4821). Try clang if this happens.

btw: cpr already includes and builds curl/libcurl and it is pure c++

**Comment by mschneider** [comment]
this is awesome

**Comment by mschneider** [comment]
do you think it's worth removing curl from the dependencies if cpr already includes it?

**Comment by Sfinx** [comment]
sure, it is extra unneeded dep:

```
root@Shiva:/opt# ls -l cpr
total 8
drwxrwxr-x 4 root root 4096 фев  9 22:33 include/
drwxrwxr-x 4 root root 4096 фев  9 22:33 lib/
root@Shiva:/opt# ls -l cpr/include
total 108
drwxr-xr-x 2 root root  4096 фев  9 22:33 cpr/
drwxr-xr-x 2 root root  4096 фев  9 22:33 curl/
-rw-r--r-- 1 root root  5297 фев  9 22:32 zconf.h
-rw-r--r-- 1 root root 94060 фев  9 22:32 zlib.h
root@Shiva:/opt# ls -l cpr/lib
total 1480
drwxrwxr-x 3 root root   4096 фев  9 22:33 cmake/
-rw-r--r-- 1 root root 318494 фев  9 22:32 libcpr.a
-rw-r--r-- 1 root root 988868 фев  9 22:32 libcurl.a
-rw-r--r-- 1 root root 194018 фев  9 22:32 libz.a
drwxrwxr-x 2 root root   4096 фев  9 22:33 pkgconfig/
root@Shiva:/opt# 
```

**Comment by bdhobare** [comment]
> sure, it is extra unneeded dep:
> 
> ```
> root@Shiva:/opt# ls -l cpr
> total 8
> drwxrwxr-x 4 root root 4096 фев  9 22:33 include/
> drwxrwxr-x 4 root root 4096 фев  9 22:33 lib/
> root@Shiva:/opt# ls -l cpr/include
> total 108
> drwxr-xr-x 2 root root  4096 фев  9 22:33 cpr/
> drwxr-xr-x 2 root root  4096 фев  9 22:33 curl/
> -rw-r--r-- 1 root root  5297 фев  9 22:32 zconf.h
> -rw-r--r-- 1 root root 94060 фев  9 22:32 zlib.h
> root@Shiva:/opt# ls -l cpr/lib
> total 1480
> drwxrwxr-x 3 root root   4096 фев  9 22:33 cmake/
> -rw-r--r-- 1 root root 318494 фев  9 22:32 libcpr.a
> -rw-r--r-- 1 root root 988868 фев  9 22:32 libcurl.a
> -rw-r--r-- 1 root root 194018 фев  9 22:32 libz.a
> drwxrwxr-x 2 root root   4096 фев  9 22:33 pkgconfig/
> root@Shiva:/opt# 
> ```

Thanks. We can do this in a follow up PR.

**Pull request merged**
